### ISSUE TITLE
Oq vc acha de criar um novo (mais um) repositório usando x.vweb para participar da rinha?

### ISSUE THREAD

**Issue by enghitalo** [marcoagpegoraro/rinha-de-backend-2024-q1-marcoagpegoraro#3]
Fiquei curioso se teria muita diferença no resultado.

https://github.com/vlang/v/tree/master/vlib/x/vweb

Você usaria, praticamente, a mesma estrutura

**Comment by marcoagpegoraro** [comment]
Obrigado pela dica! Que legal, eu não sabia que existia o x.vweb, eu vou criar um repositorio sim, e também comparar como é o desempenho de um comparado ao outro, valeu pela dica.
