### ISSUE TITLE
Parabéns

### ISSUE THREAD

**Issue by enghitalo** [marcoagpegoraro/rinha-de-backend-2024-q1-marcoagpegoraro#5]
Parabéns pelo projeto e pelo repositório muito bem documentado e pelo vídeo no youtube. Boa sorte nos resultados amanhã

**Comment by marcoagpegoraro** [comment]
Opa muito obrigado mesmo! valeu pelos pull requests, vou fazer um teste aqui comparando a performance antes e depois dos pull requests, que pena que só vi agora suas modificações kkk mas não tem problema, fica pra proxima rinha

**Comment by marcoagpegoraro** [comment]
Olha só, de fato teve uma melhora muito boa, principalmente no tempo maximo das requisições, caindo consideravelmente, vou te mandar os resultados aqui, mais uma vez gostaria de agradecer pela ajuda, no meu proximo vídeo que vai sair quando os resultados forem divulgados, vou citar sua ajuda no projeto!
Antes:
![antes](https://github.com/marcoagpegoraro/rinha-de-backend-2024-q1-marcoagpegoraro/assets/29266005/c4e2a1d1-f64d-47f9-9f7b-112dabdb5960)
Depois:
![depois](https://github.com/marcoagpegoraro/rinha-de-backend-2024-q1-marcoagpegoraro/assets/29266005/7c24670c-5b7a-4bd9-b92e-2085c7fe8cb0)

**Comment by enghitalo** [comment]
Estou sempre à disposição. Obrigado por compartilhar os resultados e divulgar a linguagem.
